name: Aaron Robins
favicon: null
layout_spectrum: 0.35693
typography_spectrum: 0.2882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afc4ef'
    - '#1d1b20'
    - '#574737'
    - '#b27b5c'
    - '#efebe0'
  brandStrength: 0.16157464543357491
  lightness: 0.2558929966762662
  saturation: 0.9210533055011183
  rhythmicContrast: 0.4367274069227278
purpose: []
